// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FSIS.App.Entities
{
    public partial class Game
    {
        public Game()
        {
            PlayerStats = new HashSet<PlayerStat>();
        }

        [Key]
        [Column("GameID")]
        public int GameId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime GameDate { get; set; }
        [Column("HomeTeamID")]
        public int HomeTeamId { get; set; }
        [Column("VisitingTeamID")]
        public int VisitingTeamId { get; set; }
        public int HomeTeamScore { get; set; }
        public int VisitingTeamScore { get; set; }

        [ForeignKey("HomeTeamId")]
        [InverseProperty("GameHomeTeams")]
        public virtual Team HomeTeam { get; set; }
        [ForeignKey("VisitingTeamId")]
        [InverseProperty("GameVisitingTeams")]
        public virtual Team VisitingTeam { get; set; }
        [InverseProperty("Game")]
        public virtual ICollection<PlayerStat> PlayerStats { get; set; }
    }
}