// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FSIS.App.Entities
{
    public partial class PlayerStat
    {
        [Key]
        [Column("PlayerStatsID")]
        public int PlayerStatsId { get; set; }
        [Column("GameID")]
        public int GameId { get; set; }
        [Column("PlayerID")]
        public int PlayerId { get; set; }
        public int Goals { get; set; }
        public int Assists { get; set; }
        public bool YellowCard { get; set; }
        public bool RedCard { get; set; }

        [ForeignKey("GameId")]
        [InverseProperty("PlayerStats")]
        public virtual Game Game { get; set; }
        [ForeignKey("PlayerId")]
        [InverseProperty("PlayerStats")]
        public virtual Player Player { get; set; }
    }
}